### ISSUE TITLE
No module named dateutil.relativedelta

### ISSUE THREAD

**Issue by elionth** [aidangomez/pygorithmic_trading#11]
Great effort.
I was wondering if you could upload the dateutil.relativedelta package for compiling.

root@localhost:~/pygorithmic-master# **python3 demo.py**
Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    from mod.Database.database import *
  File "/root/pygorithmic-master/**mod**/Database/database.py", line 3, in <module>
    from ..Resource.enumerations import SortingOrder
  File "/root/pygorithmic-master/**mod**/Resource/enumerations.py", line 1, in <module>
    from dateutil.relativedelta import *
**ImportError: No module named dateutil.relativedelta**

BTW: Added a new directory mod because it was complaining of 
valueError: Attempted relative import beyond toplevel package

**Comment by aidangomez** [comment]
@elionth Thanks for the heads-up! I'll add a "src" directory. The dateutil module should be installable via pip or pip3. The PyPi page is here: https://pypi.python.org/pypi/python-dateutil

Hopefully that fixes things for you!
